# Generated by Django 5.2.6 on 2025-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
