# Generated by Django 5.2.6 on 2025-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_latitude_alter_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
