# Generated by Django 5.2.6 on 2025-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
