# Generated by Django 5.2.6 on 2025-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shoptiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='monday_hours',
            field=models.CharField(blank=True, help_text='e.g. 9 AM - 6 PM or Closed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='sunday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
