# Generated by Django 5.2.6 on 2025-10-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_requestedshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopTiming',
        ),
    ]
