# Generated by Django 5.2.6 on 2025-10-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_delete_shoptiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedshop',
            name='products',
            field=models.TextField(blank=True, help_text='Comma-separated list of products', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.TextField(blank=True, help_text='Comma-separated list of products', null=True),
        ),
    ]
