# Generated by Django 5.2.6 on 2025-11-06 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(help_text='Enter a valid phone number (digits only, optional leading +).', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be digits only (7–15 digits, optional +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
