# Generated by Django 5.2.6 on 2025-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_product_seller_name_alter_product_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
