# Generated by Django 5.2.6 on 2026-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_product_latitude_product_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedshop',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='RequestedShop',
        ),
    ]
