# Generated by Django 5.2.6 on 2026-01-26 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_remove_requestedshop_user_delete_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(help_text='Enter a valid phone number (digits only, optional leading +).', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be digits only (7–13 digits, optional +).', regex='^\\+?\\d{7,13}$')]),
        ),
    ]
