# Generated by Django 5.2.6 on 2026-01-26 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_alter_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(help_text='Enter a valid phone number: +91 followed by 10 digits.', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be in the format +91 followed by 10 digits.', regex='^\\+91\\d{10}$')]),
        ),
    ]
