# Generated by Django 5.2.6 on 2026-02-18 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(help_text='Enter a valid phone number in E.164 format.', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Enter a valid international phone number in E.164 format (e.g., +14155552671).', regex='^\\+[1-9]\\d{7,14}$')]),
        ),
    ]
