# Generated by Django 5.2.6 on 2025-10-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
